//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "academy_behaviors")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub cadet_id: i32,
    pub points: i32,
    pub instructor_id: i32,
    pub reason: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::academy_cadets::Entity",
        from = "Column::CadetId",
        to = "super::academy_cadets::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AcademyCadets,
}

impl Related<super::academy_cadets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademyCadets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
