//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "academy_exam_content")]
pub struct Model {
    pub questions: i32,
    #[sea_orm(column_name = "questionWeight", column_type = "Double")]
    pub question_weight: f64,
    #[sea_orm(column_name = "academyExamId", primary_key, auto_increment = false)]
    pub academy_exam_id: i32,
    #[sea_orm(
        column_name = "academyExamQuestionPoolId",
        primary_key,
        auto_increment = false
    )]
    pub academy_exam_question_pool_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::academy_exam_question_pools::Entity",
        from = "Column::AcademyExamQuestionPoolId",
        to = "super::academy_exam_question_pools::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AcademyExamQuestionPools,
    #[sea_orm(
        belongs_to = "super::academy_exams::Entity",
        from = "Column::AcademyExamId",
        to = "super::academy_exams::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AcademyExams,
}

impl Related<super::academy_exam_question_pools::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademyExamQuestionPools.def()
    }
}

impl Related<super::academy_exams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademyExams.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
