//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "academy_exams")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub points: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::academy_exam_content::Entity")]
    AcademyExamContent,
    #[sea_orm(has_many = "super::academy_template_exams_relation::Entity")]
    AcademyTemplateExamsRelation,
}

impl Related<super::academy_exam_content::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademyExamContent.def()
    }
}

impl Related<super::academy_template_exams_relation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademyTemplateExamsRelation.def()
    }
}

impl Related<super::academy_exam_question_pools::Entity> for Entity {
    fn to() -> RelationDef {
        super::academy_exam_content::Relation::AcademyExamQuestionPools.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::academy_exam_content::Relation::AcademyExams
                .def()
                .rev(),
        )
    }
}

impl Related<super::academy_templates::Entity> for Entity {
    fn to() -> RelationDef {
        super::academy_template_exams_relation::Relation::AcademyTemplates.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::academy_template_exams_relation::Relation::AcademyExams
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
