//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "academy_templates")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub points: i32,
    pub behavior_points: i32,
    pub activity_points: i32,
    pub activity_hours: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::academies::Entity")]
    Academies,
    #[sea_orm(has_many = "super::academy_template_exams_relation::Entity")]
    AcademyTemplateExamsRelation,
    #[sea_orm(has_many = "super::academy_template_practices_relation::Entity")]
    AcademyTemplatePracticesRelation,
}

impl Related<super::academies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Academies.def()
    }
}

impl Related<super::academy_template_exams_relation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademyTemplateExamsRelation.def()
    }
}

impl Related<super::academy_template_practices_relation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademyTemplatePracticesRelation.def()
    }
}

impl Related<super::academy_exams::Entity> for Entity {
    fn to() -> RelationDef {
        super::academy_template_exams_relation::Relation::AcademyExams.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::academy_template_exams_relation::Relation::AcademyTemplates
                .def()
                .rev(),
        )
    }
}

impl Related<super::academy_practices::Entity> for Entity {
    fn to() -> RelationDef {
        super::academy_template_practices_relation::Relation::AcademyPractices.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::academy_template_practices_relation::Relation::AcademyTemplates
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
