//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "academy_articles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub category_id: i32,
    #[sea_orm(column_type = "Text")]
    pub content: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::academy_article_categories::Entity",
        from = "Column::CategoryId",
        to = "super::academy_article_categories::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AcademyArticleCategories,
}

impl Related<super::academy_article_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademyArticleCategories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
