//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "academy_exam_question_pools")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::academy_exam_content::Entity")]
    AcademyExamContent,
    #[sea_orm(has_many = "super::academy_exam_question_pool_questions::Entity")]
    AcademyExamQuestionPoolQuestions,
}

impl Related<super::academy_exam_content::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademyExamContent.def()
    }
}

impl Related<super::academy_exam_question_pool_questions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademyExamQuestionPoolQuestions.def()
    }
}

impl Related<super::academy_exams::Entity> for Entity {
    fn to() -> RelationDef {
        super::academy_exam_content::Relation::AcademyExams.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::academy_exam_content::Relation::AcademyExamQuestionPools
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
