//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "academy_teams")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::academy_cadets::Entity")]
    AcademyCadets,
}

impl Related<super::academy_cadets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademyCadets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
