//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "academy_exam_question_pool_questions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pool_id: i32,
    #[sea_orm(column_type = "Text")]
    pub question: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::academy_exam_question_pool_question_answers::Entity")]
    AcademyExamQuestionPoolQuestionAnswers,
    #[sea_orm(
        belongs_to = "super::academy_exam_question_pools::Entity",
        from = "Column::PoolId",
        to = "super::academy_exam_question_pools::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AcademyExamQuestionPools,
}

impl Related<super::academy_exam_question_pool_question_answers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademyExamQuestionPoolQuestionAnswers.def()
    }
}

impl Related<super::academy_exam_question_pools::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademyExamQuestionPools.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
