//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "academy_practice_options")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub percent: i32,
    pub practice_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::academy_practices::Entity",
        from = "Column::PracticeId",
        to = "super::academy_practices::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AcademyPractices,
}

impl Related<super::academy_practices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademyPractices.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
