//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "academies")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub max_members: i32,
    pub academy_template_id: i32,
    pub name: String,
    pub active: i8,
    #[sea_orm(column_type = "Text", nullable)]
    pub data: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::academy_cadets::Entity")]
    AcademyCadets,
    #[sea_orm(
        belongs_to = "super::academy_templates::Entity",
        from = "Column::AcademyTemplateId",
        to = "super::academy_templates::Column::Id",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    AcademyTemplates,
}

impl Related<super::academy_cadets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademyCadets.def()
    }
}

impl Related<super::academy_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademyTemplates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
