//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "academy_exam_question_pool_question_answers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub question_id: i32,
    #[sea_orm(column_type = "Text")]
    pub answer: String,
    pub is_correct: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::academy_exam_question_pool_questions::Entity",
        from = "Column::QuestionId",
        to = "super::academy_exam_question_pool_questions::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AcademyExamQuestionPoolQuestions,
}

impl Related<super::academy_exam_question_pool_questions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademyExamQuestionPoolQuestions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
