//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub mod prelude;

pub mod academies;
pub mod academy_article_categories;
pub mod academy_articles;
pub mod academy_behaviors;
pub mod academy_cadets;
pub mod academy_cadets_archive;
pub mod academy_events;
pub mod academy_exam_appointment_matches;
pub mod academy_exam_appointments;
pub mod academy_exam_content;
pub mod academy_exam_question_pool_question_answers;
pub mod academy_exam_question_pool_questions;
pub mod academy_exam_question_pools;
pub mod academy_exam_results;
pub mod academy_exams;
pub mod academy_practice_options;
pub mod academy_practice_results;
pub mod academy_practices;
pub mod academy_teams;
pub mod academy_template_exams_relation;
pub mod academy_template_practices_relation;
pub mod academy_templates;
pub mod academy_videos;
