//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub use super::academies::Entity as Academies;
pub use super::academy_article_categories::Entity as AcademyArticleCategories;
pub use super::academy_articles::Entity as AcademyArticles;
pub use super::academy_behaviors::Entity as AcademyBehaviors;
pub use super::academy_cadets::Entity as AcademyCadets;
pub use super::academy_cadets_archive::Entity as AcademyCadetsArchive;
pub use super::academy_events::Entity as AcademyEvents;
pub use super::academy_exam_appointment_matches::Entity as AcademyExamAppointmentMatches;
pub use super::academy_exam_appointments::Entity as AcademyExamAppointments;
pub use super::academy_exam_content::Entity as AcademyExamContent;
pub use super::academy_exam_question_pool_question_answers::Entity as AcademyExamQuestionPoolQuestionAnswers;
pub use super::academy_exam_question_pool_questions::Entity as AcademyExamQuestionPoolQuestions;
pub use super::academy_exam_question_pools::Entity as AcademyExamQuestionPools;
pub use super::academy_exam_results::Entity as AcademyExamResults;
pub use super::academy_exams::Entity as AcademyExams;
pub use super::academy_practice_options::Entity as AcademyPracticeOptions;
pub use super::academy_practice_results::Entity as AcademyPracticeResults;
pub use super::academy_practices::Entity as AcademyPractices;
pub use super::academy_teams::Entity as AcademyTeams;
pub use super::academy_template_exams_relation::Entity as AcademyTemplateExamsRelation;
pub use super::academy_template_practices_relation::Entity as AcademyTemplatePracticesRelation;
pub use super::academy_templates::Entity as AcademyTemplates;
pub use super::academy_videos::Entity as AcademyVideos;
